export { HomePage } from './HomePage'
export { ScriptUploadPage } from './ScriptUploadPage'
export { ScriptAnalysisPage } from './ScriptAnalysisPage'
export { GenerationCenterPage } from './GenerationCenterPage'
export { ConfigPage } from './ConfigPage'
